"""
Django settings for tourwebsite project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
#This is the main settings
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.api.apps.ApiConfig',
    'apps.tour.apps.TourConfig',
    'apps.system.apps.SystemConfig',
    'apps.user.apps.UserConfig',
    'apps.blog.apps.BlogConfig',

    'rest_framework',
    'rest_framework.authtoken',
    #'knox',
    #'durin',
    'djoser',
    'django_filters',
    #'rest_framework_datatables',
    'livereload',
    #'datatableview',
    'crispy_forms',
    'crispy_bootstrap5',
    #'view_breadcrumbs',
    'corsheaders',
    #'convenient_formsets',
    #'extra_views'
   
]


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS':[
        'django_filters.rest_framework.DjangoFilterBackend'
        ],
    'DEFAULT_PERMISSION_CLASSES': (
       'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'knox.auth.TokenAuthentication',
        #'durin.auth.TokenAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'tourwebsite.urls'

CORS_ORIGIN_ALLOW_ALL = False

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
#CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_FAIL_SILENTLY = True# not DEBUG #to be imported from either prod or dev settings
LOGIN_REDIRECT_URL = 'system:dashboard'
LOGOUT_REDIRECT_URL='user:login'
LOGIN_URL ="user:login"
AUTH_USER_MODEL = 'user.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'apps/user/templates/user',
            'apps/tour/templates/tour',
            'apps/system/templates/system',
            'apps/system/templates/system/common',
            'apps/blog/templates/blog',
            'apps/api/templates/api',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.system.custom_context_processors.site'
            ],
        },
    },
]

WSGI_APPLICATION = 'tourwebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = BASE_DIR/'static'
STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
}

""" REST_KNOX = {
  #'USER_SERIALIZER': 'apps.api.serializers.CustomerLoginSerializer'
  #'AUTO_REFRESH': False,
} """

DJOSER = { 
    'USER_ID_FIELD':'username',
    'SEND_ACTIVATION_EMAIL': False,
    'LOGIN_FIELD':'email',
    'HIDE_USERS':True,
    'USER_CREATE_PASSWORD_RETYPE':True,
    'SET_PASSWORD_RETYPE': True,
    'SERIALIZERS': {
        #'user_create': 'apps.api.serializers.UserCreateSerializer',
        #'user_create_password_retype':'apps.api.serializers.UserCreatePasswordRetypeSerializer',
        'user': 'apps.api.serializers.UserSerializer',
        'current_user': 'apps.api.serializers.UserSerializer',
    },
    
}
